services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev

    env_file:
      - ./Backend/.env

    environment:
      - PORT=5000
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules


  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev

    container_name: nexamind-frontend-dev

    ports:
      - "5173:5173"

    volumes:
      - ./Frontend:/app
      - frontend_node_modules:/app/node_modules

    environment:
      - CHOKIDAR_USEPOLLING=true


  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile.dev

    container_name: nexamind-gateway

    ports:
      - "4000:4000"

    volumes:
      - ./Gateway:/app
      - gateway_node_modules:/app/node_modules

    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
  gateway_node_modules: